/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PlatformProject from '../com.brand4impact.client.model/PlatformProject';
import PlatformProjectCreate from '../com.brand4impact.client.model/PlatformProjectCreate';
import PlatformProjectItemWrapper from '../com.brand4impact.client.model/PlatformProjectItemWrapper';
import PlatformProjectUpdate from '../com.brand4impact.client.model/PlatformProjectUpdate';
import RestError from '../com.brand4impact.client.model/RestError';

/**
* Project service.
* @module com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi
* @version 0.0.1
*/
export default class ProjectApi {

    /**
    * Constructs a new ProjectApi. 
    * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi
    * @class
    * @param {module:com.brand4impact.client.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.brand4impact.client.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createProject operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~createProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new project
     * This method creates a new project within a NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png 'security')](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png 'multi-tenant')](http://localhost:8080/backend/blog/home#multitenant)
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProjectCreate} project 
     * @param {File} primaryImage 
     * @param {File} secondaryImage 
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~createProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject}
     */
    createProject(project, primaryImage, secondaryImage, callback) {
      let postBody = null;
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling createProject");
      }
      // verify the required parameter 'primaryImage' is set
      if (primaryImage === undefined || primaryImage === null) {
        throw new Error("Missing the required parameter 'primaryImage' when calling createProject");
      }
      // verify the required parameter 'secondaryImage' is set
      if (secondaryImage === undefined || secondaryImage === null) {
        throw new Error("Missing the required parameter 'secondaryImage' when calling createProject");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'project': project,
        'primaryImage': primaryImage,
        'secondaryImage': secondaryImage
      };

      let authNames = ['BearerAuthentication'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = PlatformProject;
      return this.apiClient.callApi(
        '/rest/platform/project', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getProject operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~getProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a single project
     * This method returns a specific project within your tenant  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png 'security')](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png 'multi-tenant')](http://localhost:8080/backend/blog/home#multitenant)
     * @param {String} token The unique token for the campaign.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~getProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject}
     */
    getProject(token, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling getProject");
      }

      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuthentication'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlatformProject;
      return this.apiClient.callApi(
        '/rest/platform/project/{token}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getProjects operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~getProjectsCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProjectItemWrapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a set of projects
     * This method returns a set of projects within your tenant    [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png 'security')](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png 'multi-tenant')](http://localhost:8080/backend/blog/home#multitenant)[![pagination](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/brackets.png 'pagination')](http://localhost:8080/backend/blog/home#pagination)
     * @param {Object} opts Optional parameters
     * @param {String} opts.descriptionLike 
     * @param {String} opts.country The country
     * @param {String} opts.topicToken The topicToken
     * @param {Number} opts.page The number of the page. Possible values: 0 to unlimited
     * @param {Number} opts.size The number of items inside a page. Possible values: 1 to 100
     * @param {String} opts.sort The order direction for sorted results. Possible values: ASC or DESC
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~getProjectsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProjectItemWrapper}
     */
    getProjects(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'descriptionLike': opts['descriptionLike'],
        'country': opts['country'],
        'topicToken': opts['topicToken'],
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuthentication'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlatformProjectItemWrapper;
      return this.apiClient.callApi(
        '/rest/platform/project', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the switchProject operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~switchProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Switch project status
     * This method switch the status of a specific project  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png 'security')](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png 'multi-tenant')](http://localhost:8080/backend/blog/home#multitenant)
     * @param {String} token 
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~switchProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject}
     */
    switchProject(token, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling switchProject");
      }

      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuthentication'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlatformProject;
      return this.apiClient.callApi(
        '/rest/platform/project/{token}/switch', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateProject operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~updateProjectCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a project
     * This method updates an existing project  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png 'security')](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png 'multi-tenant')](http://localhost:8080/backend/blog/home#multitenant)
     * @param {String} token 
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProjectUpdate} project 
     * @param {File} primaryImage 
     * @param {File} secondaryImage 
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/ProjectApi~updateProjectCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformProject}
     */
    updateProject(token, project, primaryImage, secondaryImage, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling updateProject");
      }
      // verify the required parameter 'project' is set
      if (project === undefined || project === null) {
        throw new Error("Missing the required parameter 'project' when calling updateProject");
      }
      // verify the required parameter 'primaryImage' is set
      if (primaryImage === undefined || primaryImage === null) {
        throw new Error("Missing the required parameter 'primaryImage' when calling updateProject");
      }
      // verify the required parameter 'secondaryImage' is set
      if (secondaryImage === undefined || secondaryImage === null) {
        throw new Error("Missing the required parameter 'secondaryImage' when calling updateProject");
      }

      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'project': project,
        'primaryImage': primaryImage,
        'secondaryImage': secondaryImage
      };

      let authNames = ['BearerAuthentication'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = PlatformProject;
      return this.apiClient.callApi(
        '/rest/platform/project/{token}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
