/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PlatformTopic from '../com.brand4impact.client.model/PlatformTopic';
import PlatformTopicItemWrapper from '../com.brand4impact.client.model/PlatformTopicItemWrapper';
import RestError from '../com.brand4impact.client.model/RestError';

/**
* Topic service.
* @module com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi
* @version 0.0.1
*/
export default class TopicApi {

    /**
    * Constructs a new TopicApi. 
    * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi
    * @class
    * @param {module:com.brand4impact.client.invoker/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:com.brand4impact.client.invoker/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getTopic operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi~getTopicCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformTopic} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a single topic
     * This method returns a specific topic  A topic refers to the 17th SDG objectives [(United Nations)](https://sdgs.un.org/goals)  
     * @param {String} token The unique token for the topic.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi~getTopicCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformTopic}
     */
    getTopic(token, callback) {
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling getTopic");
      }

      let pathParams = {
        'token': token
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlatformTopic;
      return this.apiClient.callApi(
        '/rest/platform/topic/{token}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTopics operation.
     * @callback module:com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi~getTopicsCallback
     * @param {String} error Error message, if any.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformTopicItemWrapper} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a set of topics
     * This method returns all the topics according the filters  A topic refers to the 17th SDG objectives [(United Nations)](https://sdgs.un.org/goals)    [![pagination](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/brackets.png 'pagination')](http://localhost:8080/backend/blog/home#pagination)
     * @param {Object} opts Optional parameters
     * @param {String} opts.titleLike The name of the filter
     * @param {Number} opts.page The number of the page. Possible values: 0 to unlimited
     * @param {Number} opts.size The number of items inside a page. Possible values: 1 to 100
     * @param {String} opts.sort The order direction for sorted results. Possible values: ASC or DESC
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.api/TopicApi~getTopicsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformTopicItemWrapper}
     */
    getTopics(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'titleLike': opts['titleLike'],
        'page': opts['page'],
        'size': opts['size'],
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlatformTopicItemWrapper;
      return this.apiClient.callApi(
        '/rest/platform/topic', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
