/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformInvoiceEntry from './PlatformInvoiceEntry';

/**
 * The PlatformInvoice model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoice
 * @version 0.0.1
 */
class PlatformInvoice {
    /**
     * Constructs a new <code>PlatformInvoice</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoice
     */
    constructor() { 
        
        PlatformInvoice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformInvoice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoice} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoice} The populated <code>PlatformInvoice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformInvoice();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('startdate')) {
                obj['startdate'] = ApiClient.convertToType(data['startdate'], 'Date');
            }
            if (data.hasOwnProperty('enddate')) {
                obj['enddate'] = ApiClient.convertToType(data['enddate'], 'Date');
            }
            if (data.hasOwnProperty('issuedate')) {
                obj['issuedate'] = ApiClient.convertToType(data['issuedate'], 'Date');
            }
            if (data.hasOwnProperty('clientName')) {
                obj['clientName'] = ApiClient.convertToType(data['clientName'], 'String');
            }
            if (data.hasOwnProperty('clientVat')) {
                obj['clientVat'] = ApiClient.convertToType(data['clientVat'], 'String');
            }
            if (data.hasOwnProperty('clientAddress')) {
                obj['clientAddress'] = ApiClient.convertToType(data['clientAddress'], 'String');
            }
            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], {'String': [PlatformInvoiceEntry]});
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformInvoice.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformInvoice.prototype['id'] = undefined;

/**
 * @member {String} number
 */
PlatformInvoice.prototype['number'] = undefined;

/**
 * @member {Date} startdate
 */
PlatformInvoice.prototype['startdate'] = undefined;

/**
 * @member {Date} enddate
 */
PlatformInvoice.prototype['enddate'] = undefined;

/**
 * @member {Date} issuedate
 */
PlatformInvoice.prototype['issuedate'] = undefined;

/**
 * @member {String} clientName
 */
PlatformInvoice.prototype['clientName'] = undefined;

/**
 * @member {String} clientVat
 */
PlatformInvoice.prototype['clientVat'] = undefined;

/**
 * @member {String} clientAddress
 */
PlatformInvoice.prototype['clientAddress'] = undefined;

/**
 * @member {Object.<String, Array.<module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntry>>} entries
 */
PlatformInvoice.prototype['entries'] = undefined;






export default PlatformInvoice;

