/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformNgoAddress from './PlatformNgoAddress';
import PlatformNgoLegal from './PlatformNgoLegal';

/**
 * The PlatformNgo model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgo
 * @version 0.0.1
 */
class PlatformNgo {
    /**
     * Constructs a new <code>PlatformNgo</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgo
     */
    constructor() { 
        
        PlatformNgo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformNgo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgo} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgo} The populated <code>PlatformNgo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformNgo();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('vat')) {
                obj['vat'] = ApiClient.convertToType(data['vat'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = PlatformNgoAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('establishment')) {
                obj['establishment'] = ApiClient.convertToType(data['establishment'], 'Date');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('legal')) {
                obj['legal'] = PlatformNgoLegal.constructFromObject(data['legal']);
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformNgo.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformNgo.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PlatformNgo.prototype['name'] = undefined;

/**
 * @member {String} vat
 */
PlatformNgo.prototype['vat'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgoAddress} address
 */
PlatformNgo.prototype['address'] = undefined;

/**
 * @member {String} status
 */
PlatformNgo.prototype['status'] = undefined;

/**
 * @member {Date} establishment
 */
PlatformNgo.prototype['establishment'] = undefined;

/**
 * @member {String} website
 */
PlatformNgo.prototype['website'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformNgoLegal} legal
 */
PlatformNgo.prototype['legal'] = undefined;

/**
 * @member {Array.<String>} files
 */
PlatformNgo.prototype['files'] = undefined;






export default PlatformNgo;

