/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformCompanyLegalAddress from './PlatformCompanyLegalAddress';

/**
 * The PlatformCompanyLegal model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegal
 * @version 0.0.1
 */
class PlatformCompanyLegal {
    /**
     * Constructs a new <code>PlatformCompanyLegal</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegal
     */
    constructor() { 
        
        PlatformCompanyLegal.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformCompanyLegal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegal} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegal} The populated <code>PlatformCompanyLegal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformCompanyLegal();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('nid')) {
                obj['nid'] = ApiClient.convertToType(data['nid'], 'String');
            }
            if (data.hasOwnProperty('brithday')) {
                obj['brithday'] = ApiClient.convertToType(data['brithday'], 'Date');
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
            }
            if (data.hasOwnProperty('residence')) {
                obj['residence'] = ApiClient.convertToType(data['residence'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = PlatformCompanyLegalAddress.constructFromObject(data['address']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformCompanyLegal.prototype['token'] = undefined;

/**
 * @member {String} firstname
 */
PlatformCompanyLegal.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
PlatformCompanyLegal.prototype['lastname'] = undefined;

/**
 * @member {String} nid
 */
PlatformCompanyLegal.prototype['nid'] = undefined;

/**
 * @member {Date} brithday
 */
PlatformCompanyLegal.prototype['brithday'] = undefined;

/**
 * @member {String} nationality
 */
PlatformCompanyLegal.prototype['nationality'] = undefined;

/**
 * @member {String} residence
 */
PlatformCompanyLegal.prototype['residence'] = undefined;

/**
 * @member {String} email
 */
PlatformCompanyLegal.prototype['email'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegalAddress} address
 */
PlatformCompanyLegal.prototype['address'] = undefined;






export default PlatformCompanyLegal;

