/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformInvoiceEntryBase from './PlatformInvoiceEntryBase';

/**
 * The PlatformInvoiceEntry model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntry
 * @version 0.0.1
 */
class PlatformInvoiceEntry {
    /**
     * Constructs a new <code>PlatformInvoiceEntry</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntry
     */
    constructor() { 
        
        PlatformInvoiceEntry.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformInvoiceEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntry} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntry} The populated <code>PlatformInvoiceEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformInvoiceEntry();

            if (data.hasOwnProperty('concept')) {
                obj['concept'] = ApiClient.convertToType(data['concept'], 'String');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = ApiClient.convertToType(data['units'], 'Number');
            }
            if (data.hasOwnProperty('base')) {
                obj['base'] = PlatformInvoiceEntryBase.constructFromObject(data['base']);
            }
            if (data.hasOwnProperty('taxes')) {
                obj['taxes'] = PlatformInvoiceEntryBase.constructFromObject(data['taxes']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} concept
 */
PlatformInvoiceEntry.prototype['concept'] = undefined;

/**
 * @member {Number} units
 */
PlatformInvoiceEntry.prototype['units'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntryBase} base
 */
PlatformInvoiceEntry.prototype['base'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformInvoiceEntryBase} taxes
 */
PlatformInvoiceEntry.prototype['taxes'] = undefined;






export default PlatformInvoiceEntry;

