/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlatformSectorItem model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformSectorItem
 * @version 0.0.1
 */
class PlatformSectorItem {
    /**
     * Constructs a new <code>PlatformSectorItem</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformSectorItem
     */
    constructor() { 
        
        PlatformSectorItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformSectorItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformSectorItem} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformSectorItem} The populated <code>PlatformSectorItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformSectorItem();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformSectorItem.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformSectorItem.prototype['id'] = undefined;

/**
 * @member {String} title
 */
PlatformSectorItem.prototype['title'] = undefined;






export default PlatformSectorItem;

