/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlatformCampaignItem model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaignItem
 * @version 0.0.1
 */
class PlatformCampaignItem {
    /**
     * Constructs a new <code>PlatformCampaignItem</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaignItem
     */
    constructor() { 
        
        PlatformCampaignItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformCampaignItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaignItem} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaignItem} The populated <code>PlatformCampaignItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformCampaignItem();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('vouchers')) {
                obj['vouchers'] = ApiClient.convertToType(data['vouchers'], 'Number');
            }
            if (data.hasOwnProperty('budget')) {
                obj['budget'] = ApiClient.convertToType(data['budget'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('primaryImageToken')) {
                obj['primaryImageToken'] = ApiClient.convertToType(data['primaryImageToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformCampaignItem.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformCampaignItem.prototype['id'] = undefined;

/**
 * @member {String} title
 */
PlatformCampaignItem.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PlatformCampaignItem.prototype['description'] = undefined;

/**
 * @member {Number} vouchers
 */
PlatformCampaignItem.prototype['vouchers'] = undefined;

/**
 * @member {Number} budget
 */
PlatformCampaignItem.prototype['budget'] = undefined;

/**
 * @member {String} status
 */
PlatformCampaignItem.prototype['status'] = undefined;

/**
 * @member {String} primaryImageToken
 */
PlatformCampaignItem.prototype['primaryImageToken'] = undefined;






export default PlatformCampaignItem;

