/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlatformCampaign model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaign
 * @version 0.0.1
 */
class PlatformCampaign {
    /**
     * Constructs a new <code>PlatformCampaign</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaign
     */
    constructor() { 
        
        PlatformCampaign.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformCampaign</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaign} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCampaign} The populated <code>PlatformCampaign</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformCampaign();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('startdate')) {
                obj['startdate'] = ApiClient.convertToType(data['startdate'], 'Date');
            }
            if (data.hasOwnProperty('enddate')) {
                obj['enddate'] = ApiClient.convertToType(data['enddate'], 'Date');
            }
            if (data.hasOwnProperty('primaryImageToken')) {
                obj['primaryImageToken'] = ApiClient.convertToType(data['primaryImageToken'], 'String');
            }
            if (data.hasOwnProperty('secondaryImageToken')) {
                obj['secondaryImageToken'] = ApiClient.convertToType(data['secondaryImageToken'], 'String');
            }
            if (data.hasOwnProperty('videoUrl')) {
                obj['videoUrl'] = ApiClient.convertToType(data['videoUrl'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformCampaign.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformCampaign.prototype['id'] = undefined;

/**
 * @member {String} title
 */
PlatformCampaign.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PlatformCampaign.prototype['description'] = undefined;

/**
 * @member {Date} startdate
 */
PlatformCampaign.prototype['startdate'] = undefined;

/**
 * @member {Date} enddate
 */
PlatformCampaign.prototype['enddate'] = undefined;

/**
 * @member {String} primaryImageToken
 */
PlatformCampaign.prototype['primaryImageToken'] = undefined;

/**
 * @member {String} secondaryImageToken
 */
PlatformCampaign.prototype['secondaryImageToken'] = undefined;

/**
 * @member {String} videoUrl
 */
PlatformCampaign.prototype['videoUrl'] = undefined;

/**
 * @member {String} status
 */
PlatformCampaign.prototype['status'] = undefined;






export default PlatformCampaign;

