/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlatformCompanyAddress from './PlatformCompanyAddress';
import PlatformCompanyLegal from './PlatformCompanyLegal';

/**
 * The PlatformCompany model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompany
 * @version 0.0.1
 */
class PlatformCompany {
    /**
     * Constructs a new <code>PlatformCompany</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompany
     */
    constructor() { 
        
        PlatformCompany.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformCompany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompany} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompany} The populated <code>PlatformCompany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformCompany();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('vat')) {
                obj['vat'] = ApiClient.convertToType(data['vat'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = PlatformCompanyAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('legal')) {
                obj['legal'] = PlatformCompanyLegal.constructFromObject(data['legal']);
            }
            if (data.hasOwnProperty('sectorToken')) {
                obj['sectorToken'] = ApiClient.convertToType(data['sectorToken'], 'String');
            }
            if (data.hasOwnProperty('topicsToken')) {
                obj['topicsToken'] = ApiClient.convertToType(data['topicsToken'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformCompany.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformCompany.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PlatformCompany.prototype['name'] = undefined;

/**
 * @member {String} vat
 */
PlatformCompany.prototype['vat'] = undefined;

/**
 * @member {String} status
 */
PlatformCompany.prototype['status'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyAddress} address
 */
PlatformCompany.prototype['address'] = undefined;

/**
 * @member {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformCompanyLegal} legal
 */
PlatformCompany.prototype['legal'] = undefined;

/**
 * @member {String} sectorToken
 */
PlatformCompany.prototype['sectorToken'] = undefined;

/**
 * @member {Array.<String>} topicsToken
 */
PlatformCompany.prototype['topicsToken'] = undefined;






export default PlatformCompany;

