/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlatformVoucher model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformVoucher
 * @version 0.0.1
 */
class PlatformVoucher {
    /**
     * Constructs a new <code>PlatformVoucher</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformVoucher
     */
    constructor() { 
        
        PlatformVoucher.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformVoucher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformVoucher} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/PlatformVoucher} The populated <code>PlatformVoucher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformVoucher();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} token
 */
PlatformVoucher.prototype['token'] = undefined;

/**
 * @member {String} id
 */
PlatformVoucher.prototype['id'] = undefined;

/**
 * @member {String} status
 */
PlatformVoucher.prototype['status'] = undefined;

/**
 * @member {Number} amount
 */
PlatformVoucher.prototype['amount'] = undefined;

/**
 * @member {String} currency
 */
PlatformVoucher.prototype['currency'] = undefined;






export default PlatformVoucher;

