/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestError model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/RestError
 * @version 0.0.1
 */
class RestError {
    /**
     * Constructs a new <code>RestError</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/RestError
     */
    constructor() { 
        
        RestError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/RestError} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/RestError} The populated <code>RestError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestError();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} status
 */
RestError.prototype['status'] = undefined;

/**
 * @member {String} error
 */
RestError.prototype['error'] = undefined;

/**
 * @member {Date} timestamp
 */
RestError.prototype['timestamp'] = undefined;

/**
 * @member {String} zone
 */
RestError.prototype['zone'] = undefined;

/**
 * @member {String} message
 */
RestError.prototype['message'] = undefined;

/**
 * @member {Array.<String>} details
 */
RestError.prototype['details'] = undefined;






export default RestError;

