/**
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecurityUser model module.
 * @module com.brand4impact.client.invoker/com.brand4impact.client.model/SecurityUser
 * @version 0.0.1
 */
class SecurityUser {
    /**
     * Constructs a new <code>SecurityUser</code>.
     * @alias module:com.brand4impact.client.invoker/com.brand4impact.client.model/SecurityUser
     */
    constructor() { 
        
        SecurityUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecurityUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.brand4impact.client.invoker/com.brand4impact.client.model/SecurityUser} obj Optional instance to populate.
     * @return {module:com.brand4impact.client.invoker/com.brand4impact.client.model/SecurityUser} The populated <code>SecurityUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecurityUser();

            if (data.hasOwnProperty('jwtToken')) {
                obj['jwtToken'] = ApiClient.convertToType(data['jwtToken'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} jwtToken
 */
SecurityUser.prototype['jwtToken'] = undefined;

/**
 * @member {String} platform
 */
SecurityUser.prototype['platform'] = undefined;

/**
 * @member {Array.<String>} roles
 */
SecurityUser.prototype['roles'] = undefined;






export default SecurityUser;

